name: "Build and push Super Mario Docker image with static tag to Docker Hub"

on:     # runs whenver new code is pushed to main branch
   push:
     branches:
       - main

jobs:

  build_push_supermario_docker_iamge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      
      - name: Build and push Docker image
        run:  # docker.build -t '' {DockerHub URL}/{DockerHub Username}/{DockerHub Repo}:{Static Tag} {Period for current director where dockerfile is present}
          docker build -t "docker.io/svenmarley/supermariogitopsproject:1" docker.io/svenmarley/supermariogitopsproject:1 .
          docker push docker.io/svenmarley/supermariogitopsproject:1

